engines:
  eslint:
    enabled: true
ratings:
  paths:
  - src/
exclude_paths:
- "jasmine"
- "!jasmine/spec/inverted-index-test.js"
- "public"
- "src"
- "public"
- "!src/inverted-index.js"
- "!src/utils.js"
